import { Router } from 'express';
import authRoutes from './authRoutes.js';
import profileRoutes from './profileRoutes.js';
import examRoutes from './examRoutes.js';
import courseRoutes from './courseRoutes.js';
import currentAffairRoutes from './currentAffairRoutes.js';
import libraryRoutes from './libraryRoutes.js';
import revisionCapsuleRoutes from './revisionCapsuleRoutes.js';
import vocabularyRoutes from './vocabularyRoutes.js';
import testRoutes from './testRoutes.js';
import attemptRoutes from './attemptRoutes.js';
import analyticsRoutes from './analyticsRoutes.js';
import plannerRoutes from './plannerRoutes.js';
import focusRoutes from './focusRoutes.js';
import physicalRoutes from './physicalRoutes.js';
import rewardRoutes from './rewardRoutes.js';
import badgeRoutes from './badgeRoutes.js';
import doubtRoutes from './doubtRoutes.js';
import groupRoutes from './groupRoutes.js';
import mentorRoutes from './mentorRoutes.js';
import notificationRoutes from './notificationRoutes.js';
import aiRoutes from './aiRoutes.js';
import testSeriesRoutes from './testSeriesRoutes.js';
import liveClassRoutes from './liveClassRoutes.js';
import liveRoutes from './liveRoutes.js';
import leaderboardRoutes from './leaderboardRoutes.js';
import successStoryRoutes from './successStoryRoutes.js';
import wellnessRoutes from './wellnessRoutes.js';
import flashcardRoutes from './flashcardRoutes.js';
import paymentRoutes from './paymentRoutes.js';
import referralRoutes from './referralRoutes.js';
import experimentRoutes from './experimentRoutes.js';
import tierRoutes from './tierRoutes.js';
import adminRoutes from './adminRoutes.js';
import practiceRoutes from './practiceRoutes.js';
import questionRoutes from './questionRoutes.js';
import privacyRoutes from './privacyRoutes.js';
import mediaRoutes from './mediaRoutes.js';
import homeRoutes from './homeRoutes.js';
import bannerRoutes from './bannerRoutes.js';
import orderRoutes from './orderRoutes.js';
import meRoutes from './meRoutes.js';
import examPlanRoutes from './examPlanRoutes.js';
import dailyRoutineRoutes from './dailyRoutineRoutes.js';
import friendRoutes from './friendRoutes.js';
import conversationRoutes from './conversationRoutes.js';
import gamesRoutes from './gamesRoutes.js';
import searchRoutes from './searchRoutes.js';

const router = Router();

router.use('/home', homeRoutes);
router.use('/banners', bannerRoutes);
router.use('/me', meRoutes);
router.use('/exam-plan', examPlanRoutes);
router.use('/daily-routine', dailyRoutineRoutes);
router.use('/friends', friendRoutes);
router.use('/conversations', conversationRoutes);
router.use('/media', mediaRoutes);
router.use('/games', gamesRoutes);
router.use('/search', searchRoutes);
router.use('/auth', authRoutes);
router.use('/profile', profileRoutes);
router.use('/exams', examRoutes);
router.use('/courses', courseRoutes);
router.use('/current-affairs', currentAffairRoutes);
router.use('/books', libraryRoutes);
router.use('/revision-capsules', revisionCapsuleRoutes);
router.use('/vocabulary', vocabularyRoutes);
router.use('/test-series', testSeriesRoutes);
router.use('/tests', testRoutes);
router.use('/attempts', attemptRoutes);
router.use('/analytics', analyticsRoutes);
router.use('/planner', plannerRoutes);
router.use('/focus', focusRoutes);
router.use('/physical', physicalRoutes);
router.use('/wellness', wellnessRoutes);
router.use('/flashcards', flashcardRoutes);
router.use('/rewards', rewardRoutes);
router.use('/badges', badgeRoutes);
router.use('/doubts', doubtRoutes);
router.use('/groups', groupRoutes);
router.use('/mentors', mentorRoutes);
router.use('/notifications', notificationRoutes);
router.use('/payments', paymentRoutes);
router.use('/orders', orderRoutes);
router.use('/ai', aiRoutes);
router.use('/live-classes', liveClassRoutes);
router.use('/live', liveRoutes);
router.use('/leaderboard', leaderboardRoutes);
router.use('/success-stories', successStoryRoutes);
router.use('/referrals', referralRoutes);
router.use('/experiments', experimentRoutes);
router.use('/tier', tierRoutes);
router.use('/admin', adminRoutes);
router.use('/practice', practiceRoutes);
router.use('/questions', questionRoutes);
router.use('/privacy', privacyRoutes);

export default router;
